<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Add Task</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-dark">
        <span class="navbar-brand text-info mb-0 h1">Tasks</span>
        <?php if($_SESSION["loggedin"] != true): ?>
          <a href="/login" class="btn btn-outline-success" type="button">Login</a>
        <?php endif; ?>
        <?php if($_SESSION["loggedin"] == true): ?>
          <span class="navbar-text text-success"><?php echo $_SESSION['username'] ?></span>
        <?php endif; ?>

    </nav>
    <?php if(isset($data['error'])): ?>
    <div class="alert alert-danger" role="alert">
        <?php echo $data['error'] ?>
    </div>
    <?php endif; ?>
    <div class="d-flex justify-content-center">
        <form action="/task/update/<?php echo $data['id'] ?>" method="POST">
          <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" id="email" value="<?php echo $data['email'] ?>" name="email" aria-describedby="emailHelp" placeholder="Enter email">
          </div>
          <div class="form-group">
              <label for="username">Username</label>
              <input type="text" name="username" class="form-control" id="username" value="<?php echo $data['username'] ?>" placeholder="Username">
          </div>
          <div class="form-group">
              <label for="text">Text</label>
              <textarea class="form-control" name="text" id="text" rows="3"><?php echo $data['text'] ?></textarea>
          </div>
          <input class="form-check-input" type="checkbox" value="1" name="status" id="checkbox">
            <label class="form-check-label" for="checkbox">
              Completed
            </label>
          <div class="d-flex justify-content-center mt-2">
              <button type="submit" class="btn btn-primary w-100">Submit</button>
          </div>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>
