<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Tasks</title>
  </head>
  <body>
  <?php $currentPage = (isset($_GET['page']) && $_GET['page'] !== '') ? $_GET['page'] : 1; ?>
    <nav class="navbar navbar-light bg-dark">
        <span class="navbar-brand text-info mb-0 h1">Tasks</span>
        <?php if($_SESSION["loggedin"] != true): ?>
          <a href="/login" class="btn btn-outline-success" type="button">Login</a>
        <?php endif; ?>
        <?php if($_SESSION["loggedin"] == true): ?>
          <span class="navbar-text text-success"><?php echo $_SESSION['username'] ?></span>
        <?php endif; ?>

    </nav>
    <?php if(isset($_GET['edit'])): ?>
    <div class="alert alert-success" role="alert">
        Task successfully edited
    </div>
    <?php endif; ?>
    <?php if(isset($_GET['add'])): ?>
    <div class="alert alert-success" role="alert">
        Task successfully added
    </div>
    <?php endif; ?>
    <form action="" method="GET" class="row g-3 mt-1">
      <div class="col-auto">
        <select name="sortBy" class="form-select" aria-label="Sorting by">
          <option value="id">Sort By parameter</option>
          <option value="username">Username</option>
          <option value="email">Email</option>
          <option value="status">Status</option>
        </select>
      </div>
      <div class="col-auto">
        <select name="sorting" class="form-select" aria-label="Order by">
          <option >ASC</option>
          <option value="DESC">DESC</option>
        </select>
      </div>
      <input type="hidden" name="page" value="<?php echo $currentPage; ?>">
      <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Confirm</button>
      </div>
    </form>
    <div class="cards">
      <?php foreach ($data['data'] as $index => $task): ?>
      <div class="d-flex justify-content-center mt-2">
        <div class="card d-flex justify-content-center w-75">
          <div class="card-body">
            <h5 class="card-title text-center"><?php echo $task['username'] ?></h5>
            <h6 class="card-subtitle text-center mb-2"><?php echo $task['email'] ?></h6>
            <p class="card-text text-center"><?php echo $task['text'] ?></p>
            <div class="form-check d-flex justify-content-center">
              <input class="form-check-input" data-id="<?php echo $task['id'] ?>" type="checkbox" value="" id="checkbox" <?php echo $task['status'] == 1 ? 'checked' : '' ?> 
              <?php echo $_SESSION["loggedin"] == true ? '' : 'disabled' ?>>
              <label class="form-check-label" for="checkbox">
                Completed
              </label>
            </div>
            <?php if ($_SESSION["loggedin"] == true): ?>
            <div class="d-flex justify-content-center">
              <a href="/task/edit/<?php echo $task['id'] ?>" type="button" class="btn btn-primary btn-lg">Edit task</a>
            </div>
            <?php endif; ?>
          </div>
        </div>
      </div>
      <?php endforeach; ?>
    </div>

    

      <div class="d-flex justify-content-center">
        <a href="/task/add" type="button" class="btn btn-success btn-lg">Add task</a>
      </div>
      <div class="d-flex justify-content-center">
        <b><?php echo $currentPage; ?> of <?php echo $data['total_pages'] ?></b>
      </div>

    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="<?php 
          if ($currentPage - 1 > 0){printf("?page=%s&sortBy=%s&sorting=%s", ($currentPage-1), $_GET['sortBy'], $_GET['sorting']);}
          else{echo '#';}
          ?>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="<?php 
          if ($currentPage < $data['total_pages']){printf("?page=%s&sortBy=%s&sorting=%s", ($currentPage+1), $_GET['sortBy'], $_GET['sorting']);}
                                                else{echo '#';}
                                                ?>" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src= "https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="/js/index.js"></script>
  </body>
</html>
